config/routes.rb
Pastpaper::Application.routes.draw do

  #get "errors/error_404"
  #get "errors/error_500"

	get "offer/new"
	post "offer/create"
	post "mailing_lists/create"

	resources :gedcom_documents

	get 'logout' => 'sessions#destroy', :as => 'logout'
	post 'login' => 'sessions#create', :as => 'login'
	match 'forgot_password' => 'password_resets#new',:as=>'forgot_password'
	get 'profile' => 'users#index', :as => 'user_home'
	
	match 'account/deactivate' => 'users#accountdeactivate' ,:as =>'deactivateaccount'
	match 'account/changepassword' => 'users#changepassword',:as=>'changepassword'

	match 'user/registration' => 'users#new', :as => 'register'
	resources :users
	resources :password_resets
	match 'password_resets/:id/edit' => "password_resets#edit" ,:as => 'password_reset_path'
	
	resources :documents do 
		collection do 
			match 'permanent_delete/:id' => 'documents#permanently_delete',:as => :permanent_delete
			match 'publish/:id' => 'documents#publish',:as => :publish
			match 'unpublish/:id' => 'documents#unpublish',:as => :unpublish
		end
		match '/people_facts_locations' => 'documents#people_facts_locations',:as => :people_facts_loc
		resources :document_attributes
		resources :locations
		resources :document_photos
		resources :people
		#resources :document_facts
		resource :facts
		resources :document_photos
		resources :comments

	end

	get 'locations/autocomplete_location_street1'
	get 'locations/autocomplete_location_street2'
	get 'locations/autocomplete_location_town'
	get 'locations/autocomplete_location_county'
	get 'locations/autocomplete_location_state'
	get 'locations/autocomplete_location_country'

	#resources :people do
	#	resources :documents
	#end	

	match 'payments/cancel' => 'payments#paypal_cancel',:as => 'paypal_cancel'
	match 'payments/success' => 'payments#paypal_return',:as => 'paypal_return'
	match 'payments/ipn' => 'payments#create',:as => 'paypal_ipn'
	
	resources :home do 
		collection do
			#get 'document_search','simple_location_search','date_search','simple_people_search','simple_organisation_search','document_filter'
			#get 'search_results'
			#post 'search_results'
			get 'search_people'
			get 'search_locations'
			get 'search_publications'
			get 'search_dates'
			#post 'search_people'
			#get 'search_results_person'
			#post 'search_results_person'
		end
	end

	match 'documents/document_image_remove/:id' => 'document_photos#remove_image',:as=>"remove_image"
	match 'documents/make_primary_image/:id' => 'document_photos#make_primary_image',:as => :make_primary_image
	match 'person_detail/:id' => 'documents#person_detail',:as=>'person_detail'

	#match 'warmemorial' => 'documents#warmemorial_new'

	#static pages
	match 'about', :to=> 'pages#about'
	match 'contact', :to => 'pages#contact'
	match 'privacy', :to => 'pages#privacy'
	match 'terms', :to => 'pages#terms'
	match 'help', :to => 'pages#help'

	namespace :admin do
		resources :document_types
		resources :statuses
		resources :attribute_types
		resources :event_types
		resources :users
		resources :orders
		resources :documents
		match 'restore_document/:id' => 'Documents#restore_document', :as => 'restore_document'
		match 'report' => 'report#index' ,:as=>:report
		match 'report/surname_report' => 'report#surname_report',:as=>:surname_report
		match 'report/location_report' => 'report#location_report',:as=>:location_report
	end

	# Browse Links
	match 'surnames' => 'people#surnames'
	match 'surnames/:last_name' => 'people#surname_search'
	match 'tags' => 'documents#tags'
	match 'documents/tag/:id' => 'documents#tag'

	match 'bibles' => 'documents#bibles'
	match 'bibles_list' => 'documents#bibles_list'
	match 'books' => 'documents#books'
	match 'certificates' => 'documents#certificates'
	match 'deeds' => 'documents#deeds'
	match 'diaries' => 'documents#diaries'
	match 'directories' => 'documents#search_directories'
	match 'search_directories' => 'documents#search_directories'
	match 'ephemera' => 'documents#ephemera'
	match 'indentures' => 'documents#indentures'
	match 'journals' => 'documents#journals'
	match 'letters' => 'documents#letters'
	match 'magazines' => 'documents#magazines'
	match 'maps' => 'documents#search_maps'
	match 'search_maps' => 'documents#search_maps'
	match 'marriage-settlements' => 'documents#marriage_settlements'
	match 'newspapers' => 'documents#search_newspapers'
	match 'search_newspapers' => 'documents#search_newspapers'
	match 'notebooks' => 'documents#notebooks'
	match 'photos' => 'documents#photos'
	match 'postcards' => 'documents#postcards'
	match 'warmemorials' => 'documents#warmemorials'
	match 'wills' => 'documents#wills'

	match 'rollofhonour' => 'people#rollofhonour'
	
	
	#match 'search_publications' => 'documents#search_publications'

	root :to => 'home#index'

	match "/sitemap.:format",
     :controller => "home",
     :action => "sitemap",
     :conditions => { :method => :get }

	# Error handling
	# To test in development, remove condition
  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

end

app/models/person.rb
class Person < ActiveRecord::Base

	belongs_to :document
	has_many :person_events, :dependent => :destroy
	has_many :event_types
	has_many :facts ,:dependent => :destroy
	accepts_nested_attributes_for :facts, :allow_destroy => true
	validates :sex, :presence => true

 
	def full_name
		"#{self.title} " + "#{self.first_name} " + " #{self.middle_name} " + "#{self.maiden_name} " + "#{self.last_name}"     
	end
	
	def sex_color
		unless self.sex.blank?
			if self.sex=='Male'
				'#D5DEEF'
			elsif self.sex=="Female"
				'#F7D2FD'
			else
				'#66666'
			end
		end
	end

	def ancestry_link
		cj_pid         = "6185997" #commission junction referral id
		first_name     = self.first_name
		middle_name    = self.middle_name
		last_name      = self.last_name
		birth_year     = self.event_year("birth")
		birth_location = self.event_location("birth")
		residence_location = self.event_location("residence")
		death_year     = self.event_year("death")
		death_location = self.event_location("death")

		# Determine which gender to exclude
		#if self.sex = "Male"
		#	ref_gender = "&_83004003-n_xcl=m"
		#elsif self.sex = "Female"
		#	ref_gender = "&_83004003-n_xcl=f"
		#else
			ref_gender = ""	
		#end	

		cj_url              = "http://www.dpbolvw.net/click-#{cj_pid}-10505988"
		ref_url             = "?url=http://search.ancestry.co.uk/cgi-bin/sse.dll?gl=ROOT_CATEGORY&rank=1&new=1&so=3&MSAV=1&msT=1&gss=ms_f-2_s"
		ref_first_name      = "&gsfn=#{first_name}+#{middle_name}"
		ref_last_name       = "&gsln=#{last_name}"
		ref_other_last_name = "&gsln_x=XO"
		ref_birth_year      = "&msbdy=#{birth_year}"
		ref_birth_location  = "&msbpn__ftp=#{birth_location}"
		ref_residence_location = "&msrpn__ftp=#{residence_location}"
		ref_death_year      = "&msddy=#{death_year}"
		ref_death_location  = "&msdpn__ftp=#{death_location}"
		ref_collection_priority = "&cp=0"
		other_params        = "&cpxt=1&catBucket=r&uidh=r62"

		return cj_url+ref_url+ref_first_name+ref_last_name+ref_other_last_name+ref_birth_year+ref_birth_location+ref_death_year+ref_death_location+ref_residence_location+ref_gender+ref_collection_priority+other_params
	end


	def event_year(event)
		unless self.facts.blank?
			event = self.facts.find(:first, :joins => :event_type, :conditions => ["UPPER(event_types.name) = '#{event}'"])
			return event.try(:fact_year)
		#else
		#	return "?"	
		end  
	end

	def event_date(event)
		unless self.person_events.blank?
			event = self.person_events.find(:first, :joins => :event_type, :conditions => ["UPPERevent_types.name = '#{event}'"]).try(:date_event).strftime('%d %b %Y') rescue "?"
			return "#{event}"
		else
			return "?"
		end
	end

	def event_location(event)
		unless self.facts.blank?
			fact = self.facts.find(:first, :joins => :event_type, :conditions => ["UPPER(event_types.name) = '#{event}'"])
			if !fact.nil?
				if fact.location
					fact.location.full_location
				end	
			end
		end           
	end

	def event_county(event)
		unless self.facts.blank?
			fact = self.facts.find(:first, :joins => :event_type, :conditions => ["UPPER(event_types.name) = '#{event}'"])
			if fact.location
				fact.location.full_county
			end
		end           
	end

	def event_town(event)
		unless self.facts.blank?
			fact = self.facts.find(:first, :joins => :event_type, :conditions => ["UPPER(event_types.name) = '#{event}'"])
			if fact.location
				fact.location.full_town
			end
		end           
	end

	def person_events_all
		begin
			res = self.facts.find(:all, :joins => :event_type, :order=>"facts.fact_year asc") 
			if !res.blank?
				return res
			else
		 		return nil
			end
			rescue 
		end  
	end

	def person_events_except_dob
		begin
			res=self.facts.find(:all, :joins => :event_type, :conditions => ["UPPER(event_types.name) != 'BIRTH' and UPPER(event_types.name) != 'DEATH' "],:order=>"facts.fact_year asc") 
			if !res.blank?
				return res
			else
				return nil
			end
			rescue 	
		end  
	end



	def self.search_people(search_params,page,per_page=50)

		# If from date is higher than to date, swap over
		#if search_params[:date_from] > search_params[:date_to]
		#	temp = search_params[:date_from]
		#	search_params[:date_from] = search_params[:date_to]
		#	search_params[:date_to] = temp
		#end	

		condition  = ""
		condition += "UPPER(people.first_name) like  '%#{search_params[:first_name].upcase}%' AND " unless search_params[:first_name].blank?
		condition += "SOUNDEX(people.last_name) = SOUNDEX('#{search_params[:last_name]}') AND " unless search_params[:last_name].blank?
		unless condition.blank?
			condition += " status_id != 7 and is_deleted is false"
			self.paginate_by_sql("SELECT DISTINCT people.* FROM people
												LEFT JOIN documents ON documents.id = people.document_id
												WHERE #{condition} 
												ORDER BY last_name, first_name",:per_page=>per_page,:page=>page)
		else
			self.where("1=0").paginate(:per_page=>1,:page=>page)
		end
	end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
	#before_filter :require_login, :except=>[:surname_search, :show]
	before_filter :prepare_document

	def index
		@people =  @document.people
	end

	def rollofhonour
		wm = DocumentType.find(22)
		@documents = wm.people.paginate(:page =>params[:page], :order =>'last_name, first_name asc', :per_page =>50)
		@pagetitle = "Roll of Honour"
		@page_description = "Our Roll of Honour lists all of the #{wm.people.count} names we have listed on the #{Document.count(:conditions => "document_type_id = 22")} War Memorials in our database."
		render '_person_common_list'
	end
		
	
	def new
		@document_photo =  @document.document_photos.new
		
		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @user_image }
		end
	end

	def add_locations(person)
		for f in person[:facts_attributes]
			if f.second.include?(:location)
				l=f.second[:location]
				unless l.include?(:_destroy) and ActiveRecord::ConnectionAdapters::Column.value_to_boolean(l[:_destroy])
					_l=@document.locations.build(l.except(:_destroy))
					f.second[:location_id]=_l.id if _l.save!
				end
				f.second.except!(:location)
			end
		end unless person[:facts_attributes].nil?
		person
	end
	
	def create
		@person = @document.people.build(add_locations(params[:person]))
		if @person.save
			redirect_to document_people_url(@document)
		else
			render "new"
		end
	end

	def show
		@person = @document.people.find(params[:id])
		redirect_to document_people_url(@document)
	end
	
	def edit 
		@person = @document.people.find(params[:id])
	end
	
	def update
		@person = @document.people.find(params[:id])
		if @person.update_attributes(add_locations(params[:person]))
			redirect_to document_people_url(@document)
		else
			render "edit"
		end
	end

	def destroy
		@person = @document.people.find(params[:id])
		if @person
			@person.destroy    
			respond_to do |format|
				format.html { redirect_to  document_people_url(@document) }
				format.json { head :no_content }
			end
		end
	end
	
	def surname_search
		#@documents = Person.find_all_by_last_name(params[:last_name], :order=>:first_name)
		@documents = Person.where(:last_name => params[:last_name]).paginate(:page =>params[:page], :order =>'first_name', :per_page =>50)
		last_name = @documents.first.last_name
		@pagetitle = last_name+" Family Surname, Family Bibles, Letters, Wills and Old Photos"
		@page_description = "This is a list of items in The Past on Paper stock list relating to the #{last_name} family.  Browse our stocklist and find items belonging to your ancestors"
		render 'people/_person_common_list'
	end	

private

	def prepare_document
		if params[:document_id]
			if current_user.is_admin?
				@document = Document.find(params[:document_id], :include => [:document_attributes])
			else
				@document = current_user.documents.find(params[:document_id], :include => [:document_attributes])
			end  
		end  
	end 
	
end

app/helpers/people_helper.rb
module PeopleHelper

end

app/views/people/_fact_fields.html.erb
<div class="fields">
	<div class="fields form-horizontal">
		<%= f.collection_select :event_type_id, EventType.sorted_all, :id, :name, {:include_blank => "Event"},{:class=>"span2"} %> 
		Date: <%= f.select :date_modifier, date_modifiers, {:prompt=>"Exactly", :class => 'span1'} %>
		<%= f.text_field :fact_day, :placeholder=>"dd", :class=>"person-date-dd" %>
		<%= f.select :fact_month,month_array,:include_blank=>"month", :class=>""%>
		<%= f.text_field :fact_year, :placeholder=>"yyyy", :class=>"person-date-yyyy" %>
		<%= f.collection_select :location_id, @document.locations, :id, :full_location,{:include_blank => "Select Location"},{:class=>"span3"} %>
		<%= link_to_add_fields "New Location", f, :location, :replace_with %> | 
		<%= link_to_remove_fields "Remove Detail", f, :remove %>
	</div>
</div>

app/views/people/_form.html.erb
<%= render :partial => "shared/validationerror" ,:locals =>{:obj => @person}%>
<div class="fields form-horizontal">
    <div style="margin-left:0px;">
      <%= f.text_field :title, :placeholder=>"Title", :class=>"person-title" %>
      <%= f.text_field :first_name, :placeholder=>"First Name", :class=>"person-firstname" %>
      <%= f.text_field :middle_name, :placeholder=>"Middle Names", :class=>"person-middlename" %>
      <%= f.text_field :last_name, :placeholder=>"Last Name", :class=>"person-lastname"  %>
      Sex: <%= f.select :sex, people_gender, :class=>""%>
    </div>
</div>
<br />

app/views/people/_location_fields.html.erb
<%= link_to_remove_fields "<span class='button'>Use Existing Location</span>".html_safe, f, :restore_replaced %>
<div class="fields">
	<div class="controls controls-row">
		<%= f.autocomplete_field :street1, locations_autocomplete_location_street1_path, :placeholder=>'Address 1', :class=>"span6" %>
	</div>
	<div class="controls controls-row">
		<%= f.autocomplete_field :street2, locations_autocomplete_location_street2_path, :placeholder=>'Address 2', :class=>"span6" %>
	</div>
	<div class="controls controls-row">
		<%= f.autocomplete_field :town, locations_autocomplete_location_town_path, :placeholder=>'Town / City', :class=>"span6" %>
	</div>
	<div class="controls controls-row">
		<%= f.autocomplete_field :county, locations_autocomplete_location_county_path, :placeholder=>'County', :class=>"span6" %>
	</div>
	<div class="controls controls-row">
		<%= f.autocomplete_field :state, locations_autocomplete_location_state_path, :placeholder=>'State', :class=>"span6" %>
	</div>
	<div class="controls controls-row">
		<%= f.autocomplete_field :country, locations_autocomplete_location_country_path, :placeholder=>'Country', :class=>"span6" %>
	</div>
</div>

app/views/people/_person_common_list.html.erb
<% unless @page_description.blank? %>
	<div class="well">
		<%= @page_description %>
	</div>
<%end%>	

<% unless @documents.blank? %>
	<div class="well well-small" style="margin: 2px 0;">
		<div class="row-fluid">
			<div class="span1">Image</div>
			<div class="span4">Person</div>
			<div class="span4">Item Name</div>
			<div class="span1">Type</div>
			<div class="span1">Status</div>
			<div class="span1">Partners</div>
		</div>
	</div>
	<% @documents.each do |person| %>
		<div class="well well-small" style="margin: 2px 0;">
			<div class="row-fluid">
				<div class="span1"><%= link_to image_tag(person.document.default_image.photo.url(:small)), document_path(person.document),:class=>"thumbnail" unless person.document.default_image.nil? %></div>
				<div class="span4">
					<div class="span7"><%= link_to(person.full_name, document_path(person.document)) %></div>
					<div class="span5">
						<small>
							<div class="row"><small>born: <%= person.event_year("birth") rescue '' %> <%= person.event_county("birth") rescue '' %></small></div>
							<div class="row"><small>died: <%= person.event_year("death") rescue '' %> <%= person.event_county("death") rescue '' %></small></div>
						</small>
					</div>	
				</div>
				<div class="span4"> 
					<% if person.document.name.blank? %>
						<%= link_to person.document.title, document_path(person.document) %>
					<% else %>  
						<%= link_to person.document.name, document_path(person.document) %>
					<% end %>
				</div>
				<div class="span1"><%= link_to person.document.document_type_name, document_path(person.document) %></div>
				<div class="span1"><%= link_to person.document.document_status, document_path(person.document) %></div>
				<div class="span1">[<a href="<%= person.ancestry_link %>" target="_BLANK">Ancestry</a>]</div>
			</div>
		</div>
	<% end %>
	<%= will_paginate @documents ,:renderer => BootstrapLinkRenderer %>
<% end %>

app/views/people/index.html.erb
<% @pagetitle = "Edit " + page_title %>
<% sub_title = "People & Facts" %>

<div class="well">
	<div class="row-fluid">
			<h4><%= @pagetitle %></h4>
			<h6><%= sub_title %></h6>
	</div>
</div>

<div class="row-fluid">
	<%= render :partial => "documents/form_menu"%>
</div>

<div class="row-fluid">
  <div class="span11"><h4>People</h4></div>
  <div class="span1" style="margin-top:10px;">(<a href="javascript:toggle_div(helptext, 'show', 'hide', 'viewhelptext')" id="viewhelptext">hide</i></a>)</div>
</div>

<div class="row-fluid" id="helptext">
  Use the form below to enter the people referenced by your item.  All name fields are optional.  You can also add facts about the people you enter (eg birth, marriage, death, residence etc.) and associated dates, or approximate dates as well as locations entered on the locations page.  You can add as many people and as many facts as are relevant to your item.  Once you have entered people your item will be searchable on the names you entered as well as dates of facts you have associated with people.
</div>
<hr />


<% @person = @document.people.new %>
<%= form_for(@person,:url=>:document_people) do |f|%>
	<div class="row-fluid well">
		<div class="span2"><h5>Add New Person</h5></div>
		<div class="span9 userform">
				<%= render :partial => "form", :locals => {:f => f } %>
		</div>	
		<div class="span1"><%= f.submit "Save",:class=>"btn"%></div>
	</div>

	<div class="row-fluid">
		<div class="span11 offset1">
			<strong class="shadeGrey">Details about this person</strong>
			<%= f.fields_for :facts do |fact| %>
				<%= render :partial => "fact_fields", :locals => {:f => fact} %>
			<% end %>
			<br />
			<span class=""><%= link_to_add_fields "<span class='button'>+ Add More Details</span>".html_safe, f, :facts, :add %></span>
		</div>
	</div>
<%end%> 	
<hr />

<% @people.each do |person| %>
	<% unless person.new_record? %>
		<%@person = person%>
		<%= form_for(@person,:url=>document_person_path(@document,@person),:method=>:put) do |f| %>
			<div class="row-fluid well">
				<div class="span2">
					<h5><%= person.full_name%><br /></h5>
					<em>Gender: <%= person.sex %></em>
				</div>
				<div class="span8 userform">
						<%= render :partial => "form", :locals => {:f => f } %>
				</div>
				<div class="span1"><%= link_to "Delete",document_person_path(@person.document.id,@person),:method => :delete, :confirm => "Are you sure to delete?",:class=>"btn"  %></div>
				<div class="span1"><%= f.submit "Save",:class=>"btn"%></div>
			</div>

			<div class="row-fluid">
				<div class="span11 offset1">
					<strong class="shadeGrey">Details about this person</strong>
					<%= f.fields_for :facts do |fact| %>
						<%= render :partial => "fact_fields", :locals => {:f => fact} %>
					<% end %>
					<span class=""><%= link_to_add_fields "<span class='button'>+ Add More Details</span>".html_safe, f, :facts, :add %></span>
				</div>	
			</div>
		<%end%>		
		<hr />
	<% end %>		
<%end%>

app/views/people/surnames.html.erb
<% @pagetitle = "Browse all Surnames" %>
<%   
	@people = Person.all
	@male_people = Person.where("UPPER(sex) = ?","MALE".upcase)
	@female_people = Person.where("UPPER(sex) = ?","FEMALE".upcase)
	@unknown_people = Person.where("UPPER(sex) = ?","UNKNOWN".upcase)
	@surnames = Person.select("last_name,count(*) as last_name_count").group("last_name").where("last_name != ?","").order("last_name") 
	@surnames_count = @surnames.to_a.size
%>

<style>
	.surname {padding-right:20px;}
</style>
<div class="well">
	<div class="row-fluid">
		<h4><%= @pagetitle %></h4>
	</div>
</div>

<div class="row-fluid">
	<div class="span2">
		<SCRIPT "text/javascript" LANGUAGE="javascript" src="http://www.qksz.net/1e-lggm"> </SCRIPT>
	</div>
	<div class="span10">
		<div class="hero-unit">	
			There are <%= @people.count %> individuals listed in the database across <%= @surnames_count %> surnames
			(<%= @male_people.count %> Males / <%= @female_people.count %> Females / <%= @unknown_people.count %> Unknown)
		</div>	
		<div>
			<% @surnames.each do |sn| %>
				<%= link_to sn.last_name, '/surnames/'+sn.last_name, :class=>"surname"%> 
			<% end %>	
		</div>	
	</div>	
</div>