config/routes.rb
Pastpaper::Application.routes.draw do

  #get "errors/error_404"
  #get "errors/error_500"

	get "offer/new"
	post "offer/create"
	post "mailing_lists/create"

	resources :gedcom_documents

	get 'logout' => 'sessions#destroy', :as => 'logout'
	post 'login' => 'sessions#create', :as => 'login'
	match 'forgot_password' => 'password_resets#new',:as=>'forgot_password'
	get 'profile' => 'users#index', :as => 'user_home'
	
	match 'account/deactivate' => 'users#accountdeactivate' ,:as =>'deactivateaccount'
	match 'account/changepassword' => 'users#changepassword',:as=>'changepassword'

	match 'user/registration' => 'users#new', :as => 'register'
	resources :users
	resources :password_resets
	match 'password_resets/:id/edit' => "password_resets#edit" ,:as => 'password_reset_path'
	
	resources :documents do 
		collection do 
			match 'permanent_delete/:id' => 'documents#permanently_delete',:as => :permanent_delete
			match 'publish/:id' => 'documents#publish',:as => :publish
			match 'unpublish/:id' => 'documents#unpublish',:as => :unpublish
		end
		match '/people_facts_locations' => 'documents#people_facts_locations',:as => :people_facts_loc
		resources :document_attributes
		resources :locations
		resources :document_photos
		resources :people
		#resources :document_facts
		resource :facts
		resources :document_photos
		resources :comments

	end

	get 'locations/autocomplete_location_street1'
	get 'locations/autocomplete_location_street2'
	get 'locations/autocomplete_location_town'
	get 'locations/autocomplete_location_county'
	get 'locations/autocomplete_location_state'
	get 'locations/autocomplete_location_country'

	#resources :people do
	#	resources :documents
	#end	

	match 'payments/cancel' => 'payments#paypal_cancel',:as => 'paypal_cancel'
	match 'payments/success' => 'payments#paypal_return',:as => 'paypal_return'
	match 'payments/ipn' => 'payments#create',:as => 'paypal_ipn'
	
	resources :home do 
		collection do
			#get 'document_search','simple_location_search','date_search','simple_people_search','simple_organisation_search','document_filter'
			#get 'search_results'
			#post 'search_results'
			get 'search_people'
			get 'search_locations'
			get 'search_publications'
			get 'search_dates'
			#post 'search_people'
			#get 'search_results_person'
			#post 'search_results_person'
		end
	end

	match 'documents/document_image_remove/:id' => 'document_photos#remove_image',:as=>"remove_image"
	match 'documents/make_primary_image/:id' => 'document_photos#make_primary_image',:as => :make_primary_image
	match 'person_detail/:id' => 'documents#person_detail',:as=>'person_detail'

	#match 'warmemorial' => 'documents#warmemorial_new'

	#static pages
	match 'about', :to=> 'pages#about'
	match 'contact', :to => 'pages#contact'
	match 'privacy', :to => 'pages#privacy'
	match 'terms', :to => 'pages#terms'
	match 'help', :to => 'pages#help'

	namespace :admin do
		resources :document_types
		resources :statuses
		resources :attribute_types
		resources :event_types
		resources :users
		resources :orders
		resources :documents
		match 'restore_document/:id' => 'Documents#restore_document', :as => 'restore_document'
		match 'report' => 'report#index' ,:as=>:report
		match 'report/surname_report' => 'report#surname_report',:as=>:surname_report
		match 'report/location_report' => 'report#location_report',:as=>:location_report
	end

	# Browse Links
	match 'surnames' => 'people#surnames'
	match 'surnames/:last_name' => 'people#surname_search'
	match 'tags' => 'documents#tags'
	match 'documents/tag/:id' => 'documents#tag'

	match 'bibles' => 'documents#bibles'
	match 'bibles_list' => 'documents#bibles_list'
	match 'books' => 'documents#books'
	match 'certificates' => 'documents#certificates'
	match 'deeds' => 'documents#deeds'
	match 'diaries' => 'documents#diaries'
	match 'directories' => 'documents#search_directories'
	match 'search_directories' => 'documents#search_directories'
	match 'ephemera' => 'documents#ephemera'
	match 'indentures' => 'documents#indentures'
	match 'journals' => 'documents#journals'
	match 'letters' => 'documents#letters'
	match 'magazines' => 'documents#magazines'
	match 'maps' => 'documents#search_maps'
	match 'search_maps' => 'documents#search_maps'
	match 'marriage-settlements' => 'documents#marriage_settlements'
	match 'newspapers' => 'documents#search_newspapers'
	match 'search_newspapers' => 'documents#search_newspapers'
	match 'notebooks' => 'documents#notebooks'
	match 'photos' => 'documents#photos'
	match 'postcards' => 'documents#postcards'
	match 'warmemorials' => 'documents#warmemorials'
	match 'wills' => 'documents#wills'

	match 'rollofhonour' => 'people#rollofhonour'
	
	
	#match 'search_publications' => 'documents#search_publications'

	root :to => 'home#index'

	match "/sitemap.:format",
     :controller => "home",
     :action => "sitemap",
     :conditions => { :method => :get }

	# Error handling
	# To test in development, remove condition
  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def sitemap
		@url = "#{request.protocol}#{request.host_with_port}"
		@documents = Document.all
		@surnames = Person.select("distinct last_name")
	end

	def index
		@tags = Document.tag_counts_on(:tags)
		@pagetitle = "Home"
		@meta_description = "The Past on Paper links researchers of Genealogy, Family History, Local History and Home History with original historic documents in the posession of antique dealers or private individuals available to buy or view."
		@user = current_user unless current_user.blank?
		@fact_years = Fact.find :all, :order=>"fact_year ASC", :select => "DISTINCT fact_year"
	end

	def search_people
		per_page=50
		session[:search_params] = params[:search_people]
		@documents = Person.search_people(params[:search_people], params[:page], per_page)

		# Save search to db
		Search.create(:user_id     => (!current_user ? 0 : current_user.id),
		              :search_type => "Person", 
		              :firstname   => params[:search_people][:first_name], 
		              :lastname    => params[:search_people][:last_name],
		              :results     => @documents.total_entries )
		render "search_results"
	end


	def search_locations
		per_page=50
		session[:search_params] = params[:search_place]
		@documents = Location.search_location(params[:search_place], params[:page])

		# Save search to db
		Search.create(:user_id     => (!current_user ? 0 : current_user.id),
		              :search_type => "Location", 
		              :town        => params[:search_place][:city], 
		              :county      => params[:search_place][:county],
		              :country     => params[:search_place][:country],
		              :results     => @documents.total_entries )
		render "search_results"
	end

	## 
	# TODO This is all a total fudge at the moment
	def search_publications
		type=DocumentType.find(params[:search_publications][:document_type_id]).name
		if type == "Newspaper"
			params[:search_publications][:from_home_page] = true
			redirect_to :controller=>'documents', :action=>'search_newspapers'
		elsif type == "Directory"
			params[:search_publications][:from_home_page] = true
			redirect_to :controller=>'documents', :action=>'search_directories'
		elsif type == "Map"
			params[:search_publications][:from_home_page] = true
			redirect_to :controller=>'documents', :action=>'search_maps'	
		else
			per_page=50
			session[:search_params] = params[:search_publications]	
			@documents = Document.search_publications(type, params[:search_publications], params[:page])
			# save search to db
			Search.create(:user_id           => (!current_user ? 0 : current_user.id),
			              :search_type       => "Publication", 
			              :document_type_id  => params[:search_publications][:document_type_id], 
			              :results     => @documents.total_entries )
			render "search_results"
		end	
	end


	def search_dates
		per_page=50
		session[:search_params] = params[:search_dates]	
		@documents = Document.search_dates(params[:search_dates], params[:page]) 

		# save search to db
		Search.create(:user_id     => (!current_user ? 0 : current_user.id),
		              :search_type => "Date", 
		              :year        => params[:search_dates],
		              :results     => @documents.total_entries )
		render "search_results"
	end

end


## Old Code, removed but kept in place in file for now
	
#def show
#end

#def simple_people_search
#end

#def simple_location_search
#end

#def document_search
#	@document_type = DocumentType.all
#end

	#def search_results

	# search class used to save searches to db.  This is a bit messy and needs tidying up
	#search=Search.new
	#if !current_user
	#	search.user_id = 0
	#else	
	#	search.user_id = current_user.id
	#end	

	#if !params[:search_document].blank?
	#	session[:search_params] = params[:search_document]
	#	@documents = Document.search_document(params[:search_document], params[:page])

	#elsif !params[:search_people].blank?
	#	session[:search_params] = params[:search_people]
	# @documents = Document.search_people(params[:search_people], params[:page])
	# @people = Person.find_all_by_last_name(params[:search_people][:last_name])
	#	@people = Person.search_people(params[:search_people], params[:page])
	#	search.search_type="Person"
	#	search.firstname=params[:search_people][:first_name]
	#	search.lastname=params[:search_people][:last_name]
	#	search.results = @people.count

	#elsif !params[:search_place].blank?
	#	session[:search_params] = params[:search_place]
		#@documents = Document.search_location(params[:search_place], params[:page])
		#@documents = Document.search_location(params[:search_place]).paginate(:page =>params[:page], :order =>'id desc', :per_page =>50)
	#	@documents = Location.search_location(params[:search_place], params[:page])
	#	search.search_type="Location"
	#	search.town=params[:search_place][:city]
	#	search.county=params[:search_place][:county]
	#	search.country=params[:search_place][:country]
	#	search.results = @documents.count

	#elsif !params[:search_publication].blank?
	#	session[:search_params] = params[:search_publication]
	#	@documents = Document.search_publication(params[:search_publication], params[:page])
	#	search.search_type="Publication"
	#	search.document_type_id=params[:search_publication][:document_type_id]
	#	search.results = @documents.count

	#elsif !params[:search_date].blank?
	#	search.search_type="Date"
	#	session[:search_params] = params[:search_date]
	#	@documents = Document.search_date(params[:search_date], params[:page])      
	#	search.year= params[:search_date][:yyyy]
	#	search.results = @documents.count
	#else
	#	if !session[:search_params].blank? && !params[:document_filter].blank?
	#		session[:search_params][:document_type_id] = params[:document_filter][:document_type_id] unless params[:document_filter][:document_type_id].blank? 
	#		session[:search_params][:document_status] =  params[:document_filter][:document_status]
	#		per_page = params[:per_page] || 50
	#		if session[:search_params][:search_type].to_i == 1
	#			@documents = Document.search_people(session[:search_params] ,params[:page],per_page.to_i)
	#		elsif session[:search_params][:search_type].to_i == 2
	#			@documents = Document.search_location(session[:search_params] ,params[:page],per_page.to_i)
	#		elsif session[:search_params][:search_type].to_i == 3
	#			@documents = Document.search_publication(session[:search_params] ,params[:page],per_page.to_i)
	#		else			
	#		end
	#	end
		#search.results = @documents.count
	#end

	#search.save

	#if request.xhr?
	#	per_page = params[:per_page] || 50
	#	if session[:search_params][:search_type].to_i == 1
	#		@documents = Document.search_people(session[:search_params] ,params[:page],per_page.to_i)
	#	elsif session[:search_params][:search_type].to_i == 2
	#		@documents = Document.search_location(session[:search_params] ,params[:page],per_page.to_i)
	#	elsif session[:search_params][:search_type].to_i == 3
	#		@documents = Document.search_publication(session[:search_params] ,params[:page],per_page.to_i)
	#	else
	#	end
	#end
#end

app/helpers/home_helper.rb
module HomeHelper
  #include ActsAsTaggableOn::TagsHelper
end	

app/views/home/_advert_left.html.erb
<div class="span4 lightyellow well searchbox">
<SCRIPT type="text/javascript" LANGUAGE="javascript" src="http://www.qksz.net/1e-lgws"> </SCRIPT>
</div>

app/views/home/_bottom_content.html.erb
<div class="row well">
  <div class="span6">
    <div class="row-fluid">
      <div class="span2"><a href="http://blog.pastonpaper.com" target="_TOP"><%= image_tag("icons/blog.jpg",:height=>"50", :width=>"50",  :title=>"Past on paper Blog")%></a></div>
      <div class="span6"><h3>From <a href="http://blog.pastonpaper.com" target="_TOP">The Blog</a></h3></div>
    </div>
    <% @latest_blog_posts = RSS::Parser.parse(open('http://blog.pastonpaper.com/?feed=rss2').read, false).items[0...5] %>
    <% unless @latest_blog_posts.nil? %>
      <ul>
        <% @latest_blog_posts.each do |post| %>
          <% if nil != post && post.respond_to?(:pubDate) %>
            <li>
              <%= link_to post.title, post.link, :target => "_blank" %>
              (<%= time_ago_in_words(post.pubDate) %> ago)<br/>
              <%= truncate(post.description, :length=>140, :omission => '...').html_safe %>
            </li>
          <% end %>
        <% end %>
      </ul>
    <% else %>
      <p>
        <em>No blog posts to show.</em>
      </p>
    <% end %>
  </div>

  <div class="span6">
    <div class="row-fluid">      
      <div class="span2"><a href="http://www.facebook.com/pastonpaper" target="_TOP"><%= image_tag("icons/facebook.jpg",:height=>"50", :width=>"50",  :title=>"Past on Paper on Facebook")%></a></div>
      <div class="span6"><h3>From <a href="http://www.facebook.com/pastonpaper" target="_TOP">Facebook</a></h3></div>
    </div>
    <% @latest_facebook_posts = RSS::Parser.parse(open('http://www.facebook.com/feeds/page.php?id=132623756852735&format=rss20').read, false).items[0...5] %> 
    <% unless @latest_facebook_posts.nil? %>
      <ul>
        <% @latest_facebook_posts.each do |post| %>
          <% if nil != post && post.respond_to?(:pubDate) %>
            <li>
              <%= link_to post.title.html_safe, post.link, :target => "_blank" %>
              (<%= time_ago_in_words(post.pubDate) %> ago)
            </li>
          <% end %>
        <% end %>
      </ul>
    <% else %>
      <p>
        <em>No blog posts to show.</em>
      </p>
    <% end %>
  </div>
</div>

app/views/home/_browse.html.erb
<div class="row">
	Browse all: 
	<%= link_to "Family Bibles", bibles_path %>&nbsp&nbsp|&nbsp&nbsp
	<%= link_to "Old Photos", photos_path %>&nbsp&nbsp|&nbsp&nbsp
	<%= link_to "Antique Maps", maps_path %>&nbsp&nbsp|&nbsp&nbsp
	<%= link_to "Old Postcards", postcards_path %>&nbsp&nbsp|&nbsp&nbsp
	<%= link_to "Kelly's, White's and Pigot's Directories", directories_path %>&nbsp&nbsp|&nbsp&nbsp
	<%= link_to "Ephemera", ephemera_path %>&nbsp&nbsp|&nbsp&nbsp
	<%= link_to "Antique Newspapers", newspapers_path %>&nbsp&nbsp|&nbsp&nbsp
	<%= link_to "Old Wills", wills_path %> 
</div>

app/views/home/_featured_items.html.erb
<% featured_items = 6 %>
<% featured_documents = Document.show_featured_documents.sort_by{ rand }.slice(0..(featured_items-1)) %>

<div class="row">
  <% featured_documents.each do |document|  %>  
    <div class="span2 well featuredbox">
      <% if document.name.blank? %>
        <% doctitle = document.title%>
      <% else %>  
	      <% doctitle = document.name %>
      <% end %>
      <div class="row-fluid"><center><%= link_to image_tag(document.default_image.photo.url(:small), :title=>doctitle, :class=>"img-polaroid"), document_path(document) unless document.default_image.nil? %></center></div>
      <div class="row-fluid"><%= truncate(doctitle, :length => 50, :omission => '...') %></div>
    </div>
  <%end%>
</div>

app/views/home/_latest_items.html.erb
<div class="row">
  <div class="hidden-phone">
    <ul class="thumbnails">
	    <% latest_items(12).each do |document| %>
		    <% if document.name.blank? %>
			    <% doctitle = document.title%>
		    <% else %>  
			    <% doctitle = document.name %>
		    <% end %>
		    <li class="span1">
		    <% if document.default_image.present? %>
		      <%= link_to image_tag(document.default_image.photo.url(:small), :title => doctitle, :class=>"img-rounded"), document_path(document) unless document.default_image.nil? %>
		    <%end%>
		    </li>
	    <% end %>
    </ul>	
  </div>
</div>

app/views/home/_latest_paper.html.erb
<div class="row">
  <div class="hidden-phone">
    <ul class="thumbnails">
	    <% latest_paper(12).each do |document| %>
		    <% if document.name.blank? %>
			    <% doctitle = document.title%>
		    <% else %>  
			    <% doctitle = document.name %>
		    <% end %>
		    <li class="span1">
		    <% if document.default_image.present? %>
		      <%= link_to image_tag(document.default_image.photo.url(:small), :title => doctitle, :class=>"img-rounded"), document_path(document) unless document.default_image.nil? %>
		    <%end%>
		    </li>
	    <% end %>
    </ul>	
  </div>
</div>

app/views/home/_latest_stone.html.erb
<div class="row">
  <div class="hidden-phone">
    <ul class="thumbnails">
	    <% latest_stone(12).each do |document| %>
		    <% if document.name.blank? %>
			    <% doctitle = document.title%>
		    <% else %>  
			    <% doctitle = document.name %>
		    <% end %>
		    <li class="span1">
		    <% if document.default_image.present? %>
		      <%= link_to image_tag(document.default_image.photo.url(:small), :title => doctitle, :class=>"img-rounded"), document_path(document) unless document.default_image.nil? %>
		    <%end%>
		    </li>
	    <% end %>
    </ul>	
  </div>
</div>

app/views/home/_search_filter.html.erb
<% if site.preview_mode = false %>
  <% if @documents.count > 1 %>
    <div class="pull-right">
      <%= form_for :document_filter, :url => search_results_home_index_path, :html => {:class=>"form-inline"} do |f| %>
        You can filter your search : 
        <%= f.collection_select :document_type_id , DocumentType.paper.alphabetically , :id,:name,{:prompt=>"Select document type"} %>
        <%= f.collection_select :document_status , Status.for_filter , :id,:name,{:prompt=>"Select document status"}  %>
        <%= f.submit "Go",:class=>"btn btn-primary"%>
      <%end%>
    </div>
  <%end%>
<% end %>

app/views/home/_search_form_browse.html.erb
<% browse = capture do %>
	<div id="publication" class="">
		<%= form_for :search_publications, :url => search_publications_home_index_path, :method=>'get', :html => {:class=>"form-inline"} do |f| %>
			<%= f.hidden_field :search_type, :value=>3 %>
			<%= f.collection_select :document_type_id, DocumentType.paper.alphabetically, :id, :name, :prompt => "Please select type", :class => 'text  input-large' %>
			<%= f.submit "",:class=>"btn btn-primary pull-right",:id=>"searchbyplacebtn", :value=>"Browse" %>
		<%end%>
	</div>
<%end%>	

<% datesearch = capture do %>
	<div id="place" class="">
		<%= form_for :search_dates, :url => search_dates_home_index_path, :method=>'get', :html => {:class=>"form-inline"} do |f| %>
			<%= f.hidden_field :search_type, :value=>4 %>
      <%= f.select(:yyyy, @fact_years.map(&:fact_year), {:include_blank => 'Select a Year'}, :class=>"search-query input-medium") %>
  		<%= f.submit "",:class=>"btn button btn-primary pull-right",:id=>"searchbyplacebtn", :value=>"Search" %>
		<%end%>
	</div>
<%end%>	


<div class="span4 lightyellow well searchbox">
  <h2>Browse</h2>
  <p class="muted">Browse by item type</p>    
  <%= browse %>
     
  <p class="muted">Search for a date in history</p>
  <%= datesearch %>
</div>

app/views/home/_search_form_person.html.erb
<% personsearch = capture do %>
	<div id="person" class="">
		<%= form_for :search_people, :url => search_people_home_index_path, :method=>'get', :html => {:class=>""} do |f| %>
			<%= f.hidden_field :search_type, :value=>1 , :class=>"input-small"%>
			<%= f.text_field :first_name,{:placeholder => "First Name",:size=>25, :class=>"input-small"} %>
			<%= f.text_field :last_name,{:placeholder => "Last Name",:size=>25, :class=>"input-small"} %>
      <br />
		  <%#= f.select(:date_from, @fact_years.map(&:fact_year), {:include_blank => 'From'}, :class=>"search-query input-small") %>
		  <%#= f.select(:date_to, @fact_years.map(&:fact_year), {:include_blank => 'To'}, :class=>"search-query input-small") %>
			<%= f.submit "",:class=>"btn btn-primary pull-right",:id=>"searchbyperson", :value=>"Search" %>
		<% end %>
	</div>
<%end%>

<div class="span4 lightblue well searchbox">
  <h2>Person Search</h2>
  <p class="muted">Search for your ancestors in our large collection of historic documents including Family Bibles, Photographs, Wills, Letters and Postcards</p>
  <%= personsearch %>    
</div>

app/views/home/_search_form_place.html.erb
<% placesearch = capture do %>
	<div id="place" class="">
		<%= form_for :search_place, :url => search_locations_home_index_path, :method=>'get', :html => {:class=>""} do |f| %>
			<%= f.hidden_field :search_type, :value=>2 %>
			<!-- Search place -->
			<%= f.text_field :city,{:placeholder => "Town", :class=>"input-small"} %>
			<%= f.text_field :county,{:placeholder => "County", :class=>"input-medium"} %>
      <%= f.select(:country, db_countries.map(&:country), {:include_blank => 'Select a Country'}, :class=>"input-medium") %>
      <% if site.preview_mode = false %>
			  <!-- Search Dates -->
        <br />
			  <label>DATE FROM</label>
			  <%= f.text_field :date_from, {:placeholder=>"YYYY", :size => 10, :class=>"search_input_date input-mini"} %>
			  <label>DATE FROM</label>
			  <%= f.text_field :date_to, {:placeholder=>"YYYY",:size => 10, :class => "search_input_date input-mini"} %>
      <%end%>
			<%= f.submit "",:class=>"btn button btn-primary pull-right",:id=>"searchbyplacebtn", :value=>"Search" %>
		<%end%>
	</div>
<%end%>	

<div class="span4 lightgreen well searchbox">
  <h2>Place Search</h2>
  <p class="muted">Search for your home or town in our large collection of historic documents including Family Bibles, Photographs, Wills, Letters and Postcards</p>
  <%= placesearch %>
</div>

app/views/home/index.html.erb
<%= render 'latest_paper' %>
<%= render 'latest_stone' %>
<% if !current_user %>
  <div class="row">
    <div class="hero-unit .hidden-phone">
      <h3>Welcome to The Past on Paper!</h3>
      <p>Our aim is to reunite Genealogists and Local Historians with the items from their past, hidden in Private Collections and dealerships around the world.  From Family Bibles and Old Photos, to Wills, Diaries and Letters, Login or Register now for full access to database. Registration is free and enables you to view the genealogical data within the items on the site</p>
    </div>
  </div>
<%end%>

<div class="row">
  <%= render 'advert_left' %>
  <%= render 'search_form_person' %>
  <%= render 'search_form_place' %>
  <%#= render 'search_form_browse' %>
</div>

<div class="row well">
  <center><%= banner_ad %></center>
</div>

<%= render 'featured_items' %>

<div class="row well">
  <center>
    <script language="javascript" type="text/javascript">
      var myTarget="http://track.webgains.com/click.html?wglinkid=85629&wgcampaignid=122233&js=0";
      var uri = "http://track.webgains.com/link.html?wglinkid=85629&wgcampaignid=122233";
      document.write('<a href="'+myTarget+'" target="_blank" onMouseOver="window.status=\'http://www.historic-newspapers.co.uk\';return true;" onMouseOut="window.status=\'\'"><img src="'+uri+'" width="728" height="90" border="0" alt="Historic Newspapers"/></a>');
    </script>
  <center>
</div>

<%= render 'bottom_content' %>

app/views/home/search_results.html.erb
<% @pagetitle = "Search Results" %>

<div class="alert alert-info">
  <div class="lead">
      <% if @documents.empty? %>
        Sorry, Nothing Found matching your search criteria
      <% else %>
        <%= @documents.total_entries %> <%= @documents.first.class.name.sub("Controller", "").pluralize %> Found
      <% end %>  
  </div>
</div>

<div class="search_results_container">
  <div class="row-fluid">
    <div class="pull-left">
	    <%= link_to "Back" ,root_path,:class=>"btn"%>
    </div>

    <% if session[:search_params][:document_type_id].to_i == 4 %>
      <div class="span1"></div>
      <div class="row-fluid" style="margin-bottom:10px;">
        <div class="">
          <script language="javascript" type="text/javascript">
          var myTarget='http://track.webgains.com/click.html?wglinkid=243675&wgcampaignid=122233&js=0';
          var uri = 'http://track.webgains.com/link.html?wglinkid=243675&wgcampaignid=122233';
          document.write('<a href="'+myTarget+'" target="_blank" onMouseOver="window.status=\'http://www.historic-newspapers.co.uk\';return true;" onMouseOut="window.status=\'\'"><img src="'+uri+'" width="728" height="90" border="0" alt="Historic Newspapers - Original Newspaper Gifts"/></a>');
          </script>
        </div>
      </div>
    <% else %>
      <div class="row-fluid" style="margin-bottom:10px;">
        <div class="pull-right">
          <%= banner_ad %>
        </div>
      </div>
    <%end%>

    <%= render "search_filter" %>

  </div>

  <div>
 
    <% if session[:search_params][:search_type].to_i == 1 %>
      <%= render "people/person_common_list"%> 
    <% elsif session[:search_params][:search_type].to_i == 2 %>
      <%= render "locations/location_common_list"%> 
    <% else %>
      <%= render "documents/document_common_list"%> 
    <% end %>


    <%= will_paginate @documents, :renderer => BootstrapLinkRenderer %>


    <% if @documents.blank? %>
      <br />
      <div class="bottom_container row-fluid">
        <%= render 'bottom_content' %>
      </div>
    <% end %>
  
  </div>
</div>

app/views/home/search_results.js.erb
$("#document_results").html("<%= escape_javascript(render :partial => 'search_result')%>");