config/routes.rb
Pastpaper::Application.routes.draw do

  #get "errors/error_404"
  #get "errors/error_500"

	get "offer/new"
	post "offer/create"
	post "mailing_lists/create"

	resources :gedcom_documents

	get 'logout' => 'sessions#destroy', :as => 'logout'
	post 'login' => 'sessions#create', :as => 'login'
	match 'forgot_password' => 'password_resets#new',:as=>'forgot_password'
	get 'profile' => 'users#index', :as => 'user_home'
	
	match 'account/deactivate' => 'users#accountdeactivate' ,:as =>'deactivateaccount'
	match 'account/changepassword' => 'users#changepassword',:as=>'changepassword'

	match 'user/registration' => 'users#new', :as => 'register'
	resources :users
	resources :password_resets
	match 'password_resets/:id/edit' => "password_resets#edit" ,:as => 'password_reset_path'
	
	resources :documents do 
		collection do 
			match 'permanent_delete/:id' => 'documents#permanently_delete',:as => :permanent_delete
			match 'publish/:id' => 'documents#publish',:as => :publish
			match 'unpublish/:id' => 'documents#unpublish',:as => :unpublish
		end
		match '/people_facts_locations' => 'documents#people_facts_locations',:as => :people_facts_loc
		resources :document_attributes
		resources :locations
		resources :document_photos
		resources :people
		#resources :document_facts
		resource :facts
		resources :document_photos
		resources :comments

	end

	get 'locations/autocomplete_location_street1'
	get 'locations/autocomplete_location_street2'
	get 'locations/autocomplete_location_town'
	get 'locations/autocomplete_location_county'
	get 'locations/autocomplete_location_state'
	get 'locations/autocomplete_location_country'

	#resources :people do
	#	resources :documents
	#end	

	match 'payments/cancel' => 'payments#paypal_cancel',:as => 'paypal_cancel'
	match 'payments/success' => 'payments#paypal_return',:as => 'paypal_return'
	match 'payments/ipn' => 'payments#create',:as => 'paypal_ipn'
	
	resources :home do 
		collection do
			#get 'document_search','simple_location_search','date_search','simple_people_search','simple_organisation_search','document_filter'
			#get 'search_results'
			#post 'search_results'
			get 'search_people'
			get 'search_locations'
			get 'search_publications'
			get 'search_dates'
			#post 'search_people'
			#get 'search_results_person'
			#post 'search_results_person'
		end
	end

	match 'documents/document_image_remove/:id' => 'document_photos#remove_image',:as=>"remove_image"
	match 'documents/make_primary_image/:id' => 'document_photos#make_primary_image',:as => :make_primary_image
	match 'person_detail/:id' => 'documents#person_detail',:as=>'person_detail'

	#match 'warmemorial' => 'documents#warmemorial_new'

	#static pages
	match 'about', :to=> 'pages#about'
	match 'contact', :to => 'pages#contact'
	match 'privacy', :to => 'pages#privacy'
	match 'terms', :to => 'pages#terms'
	match 'help', :to => 'pages#help'

	namespace :admin do
		resources :document_types
		resources :statuses
		resources :attribute_types
		resources :event_types
		resources :users
		resources :orders
		resources :documents
		match 'restore_document/:id' => 'Documents#restore_document', :as => 'restore_document'
		match 'report' => 'report#index' ,:as=>:report
		match 'report/surname_report' => 'report#surname_report',:as=>:surname_report
		match 'report/location_report' => 'report#location_report',:as=>:location_report
	end

	# Browse Links
	match 'surnames' => 'people#surnames'
	match 'surnames/:last_name' => 'people#surname_search'
	match 'tags' => 'documents#tags'
	match 'documents/tag/:id' => 'documents#tag'

	match 'bibles' => 'documents#bibles'
	match 'bibles_list' => 'documents#bibles_list'
	match 'books' => 'documents#books'
	match 'certificates' => 'documents#certificates'
	match 'deeds' => 'documents#deeds'
	match 'diaries' => 'documents#diaries'
	match 'directories' => 'documents#search_directories'
	match 'search_directories' => 'documents#search_directories'
	match 'ephemera' => 'documents#ephemera'
	match 'indentures' => 'documents#indentures'
	match 'journals' => 'documents#journals'
	match 'letters' => 'documents#letters'
	match 'magazines' => 'documents#magazines'
	match 'maps' => 'documents#search_maps'
	match 'search_maps' => 'documents#search_maps'
	match 'marriage-settlements' => 'documents#marriage_settlements'
	match 'newspapers' => 'documents#search_newspapers'
	match 'search_newspapers' => 'documents#search_newspapers'
	match 'notebooks' => 'documents#notebooks'
	match 'photos' => 'documents#photos'
	match 'postcards' => 'documents#postcards'
	match 'warmemorials' => 'documents#warmemorials'
	match 'wills' => 'documents#wills'

	match 'rollofhonour' => 'people#rollofhonour'
	
	
	#match 'search_publications' => 'documents#search_publications'

	root :to => 'home#index'

	match "/sitemap.:format",
     :controller => "home",
     :action => "sitemap",
     :conditions => { :method => :get }

	# Error handling
	# To test in development, remove condition
  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

end

app/models/document_type.rb
class DocumentType < ActiveRecord::Base

	has_many :documents
	has_many :people, :through => :documents

	scope :alphabetically, :order => "name ASC"
	scope :paper, where("paper = 1")
	scope :stone, where("stone = 1")

end

app/models/document_view.rb
class DocumentView < ActiveRecord::Base
	belongs_to :user
	belongs_to :document
end

app/controllers/admin/documents_controller.rb
class Admin::DocumentsController < ApplicationController
 before_filter :require_admin
  # GET /document_types
  # GET /document_types.json
  def index
    conditions = []
    if !params[:document_filter].blank?
        document_type_id = params[:document_filter][:document_type_id] 
        status_id =  params[:document_filter][:document_status] 
        if !document_type_id.blank? && !status_id.blank?
          conditions = ["document_type_id = ? and status_id = ?",document_type_id,status_id]
        elsif !document_type_id.blank?
          conditions = ["document_type_id = ?",document_type_id]
        elsif !status_id.blank?
           conditions = ["status_id = ?",status_id]
        else
          conditions = []
        end
    end 
    
    @documents = Document.where(conditions).paginate(:page =>params[:page], :order =>'id desc', :per_page =>50)
  end


  # to restore deleted document
  def restore_document
    @document = Document.find(params[:id])
      if @document.update_attributes(:is_deleted => false)
        redirect_to admin_documents_url, notice: 'Document  was successfully restored.' 
        
      else 
        redirect_to admin_documents_url, notice: 'Document  was successfully restored.' 
      end
    
  end

  # DELETE /document_types/1
  # DELETE /document_types/1.json
 end

app/helpers/document_helper.rb
module DocumentHelper

	def page_title
		if @document.name.blank?
			return @document.title
		else
			return @document.name
		end
	end

	def document_summary
		document_summary = "#{page_title}"
		document_summary << ". "

		document_summary << "This #{@document.document_type.name} mentions #{@document.people.count} individuals and #{@document.locations.count} locations"

		if @document.earliest_fact_year == 0 && @document.latest_fact_year == 0
			document_summary << ". "
		elsif @document.earliest_fact_year == @document.latest_fact_year
			document_summary <<" and covers events in #{@document.earliest_fact_year}."
		else
			document_summary << "and covers events from #{@document.earliest_fact_year} to #{@document.latest_fact_year}."
		end
			
		if @document.people.any?
			if @document.people.count == 1
			document_summary << "Surname listed is #{@document.last_name_list}." 
		  else
			document_summary << "Surnames listed are #{@document.last_name_list}." 
		  end
		end

		return document_summary
	end


	def increment_view_counter
		Document.increment_counter(:views, @document.id)
	end

	##
	# Returns an Array of order distinct publication years for the Document type named
	def publication_years(publication_type)
		publication_type_id = DocumentType.find_by_name(publication_type).id
		condition= ""
		DocumentAttribute.find_all_by_attribute_type_id(2, :joins=> :document, :conditions => "documents.document_type_id = #{publication_type_id}", :select=>"distinct attribute_year", :order=>"attribute_year ASC")
	end

	##
	# returns url of current document for facebook
	def share_url
		return document_url(@document)
	end

	##
	# Returns data for current document for sharing
	def share_data
		if @document.name.blank?
			share_data['data']= @document.try(:title)
			share_data['description'] = @document.try(:title)
		else
			share_data['data']=@document.try(:name)
			share_data['description'] = @document.try(:name)
		end
		return share_data
	end

	##
	# Returns thumbnail image url
	def fb_img
		if !@document.blank? && !@document.document_photos.blank?
			@fb_img = @document.default_image.photo.url(:thumb)
		end
	end

end

app/views/documents/_document_comments.html.erb
<h4>Comments</h4>

<div class="row-fluid">
	<%#= render @document.comments %>
</div>

<div class="row-fluid">
	<%= render :file => 'comments/new' %>
</div>	

app/views/documents/_document_filter.html.erb
<% if site.preview_mode = false %>
  <% if @documents.count > 1 %>
    <div class="span8">
      <%= form_for :document_filter, :html => {:class=>"form-inline",:method=>:get} do |f| %>
        Filter by : 
        <% if !params[:document_filter].blank? &&  !params[:document_filter][:document_type_id].blank?%>
          <%= f.collection_select :document_type_id , DocumentType.alphabetically , :id,:name,{:prompt=>"All",:selected => params[:document_filter][:document_type_id]} %>
        <% else %>
          <%= f.collection_select :document_type_id , DocumentType.alphabetically , :id,:name,{:prompt=>"All"} %>
        <% end%>
        <% if !params[:document_filter].blank? && !params[:document_filter][:document_status].blank?%>
          <%= f.collection_select :document_status , Status.for_filter , :id,:name,{:prompt=>"All",:selected => params[:document_filter][:document_status]}  %>
        <% else %>
          <%= f.collection_select :document_status , Status.for_filter , :id,:name,{:prompt=>"All"}  %>
        <% end%>
        <%= f.submit "Go",:class=>"btn btn-primary"%>
      <%end%>
    </div>
  <%end%>
<%end%>  

app/views/documents/_form_item_details.html.erb
<div class="row-fluid">
  <div class="span11"><h4>Item Details</h4></div>
  <div class="span1" style="margin-top:10px;">(<a href="javascript:toggle_div(helptext, 'show', 'hide', 'viewhelptext')" id="viewhelptext">hide</i></a>)</div>
</div>

<div class="row-fluid" id="helptext">
  <h5 class="text-info">Adding an item is a simple 5 step process where you are asked to enter standard details about your item.</h5>
  On this page, you are asked to enter the basic information relating to the physical item, such as the title the weight and the condition, as well as any internal stock numbers and names you may have for the item as well as a description.  You can also enter a comma seperated listof tags.  Most fields are optional, though the weight is used to calculate the postage price if you are listing the item for sale - if you do not enter a weight, the item will be listed as free postage.<br /><br />
  Once you have saved your item below, you can then add further information about your item, including publication information, images, and topographical & genealogical data.
</div>
<hr />


<div class="controls controls-row">
  <%= f.text_field :stock_number , {:placeholder => "Stock Number" , :class => "span2" }%>
  <%= f.collection_select :status_id, Status.alphabetically, :id, :name, :prompt => "Select Item Status", :class =>"span2"  %>
  <%= f.collection_select :document_type_id, DocumentType.alphabetically, :id, :name, :prompt =>"Select Item Type", :class =>"span4" %>
</div>
<br />
<div class="controls controls-row">
  <%= f.text_field :name , {:placeholder => "Item Name (the friendly name of the item, eg Family Bible of John Smith)" , :class => "span9" }%>
</div>
<br />
<div class="controls controls-row">
  <%= f.text_field :title , {:placeholder => "Item Title (the published title if applicable)" , :class => "span9" }%>
</div>
<br />
<div class="controls controls-row">
  <%= f.number_field :length,  {:placeholder=>"length (mm)",:class => 'span2'} %>
  <%= f.number_field :width,   {:placeholder=>"width (mm)", :class => 'span2'} %>
  <%= f.number_field :depth,   {:placeholder=>"depth (mm)", :class => 'span2'} %>
  <%= f.number_field :weight,  {:placeholder=>"weight (g)", :class => 'span2'} %>
</div>
<br />
<div class="controls controls-row">
  <%= f.text_field :condition,  {:placeholder=>"Describe Item Condition",:class => 'span9'} %>
</div>
<br />
<div class="controls controls-row">
  <%= f.text_field :binding,  {:placeholder=>"Describe Item Binding if applicable",:class => 'span9'} %>
</div>
<br />
<div class="controls controls-row">
  <%= f.text_area :comment, {:placeholder=>"Item Details",:class => 'textarea span9'} %>
</div>
<br />
<div class="controls controls-row">
  <%= f.text_field :tag_list,  {:placeholder=>"Enter some tags, seperated by commas (eg Victorian, Humour, Seaside)",:class => 'textarea span9'} %>
</div>
<br />
<div class="controls controls-row">
  <div class="span7"></div>
  <%= f.text_field :sale_price,  {:placeholder=>"Price",:class => 'span2'} %>
</div>

app/views/documents/_form_menu.html.erb
<div class="navbar">
	<div class="navbar-inner">

		<ul class="nav nav-bar">
			<% unless @document.new_record? %>
				<li><%= link_to_unless_current("View Item", document_path(@document))  %></li>
				<% unless current_page?(edit_document_path(@document)) %>
					<li><%= link_to_unless_current("Item Details", edit_document_path(@document)) %></li>
				<% else %>
					<li class="active"><a>Item Details</a></li>
				<% end %>	
			<% end %>

			<% unless @document.new_record? %>
				<% unless current_page?(document_document_attributes_path(@document)) %>
					<li><%= link_to("Publication Info", document_document_attributes_path(@document)) %></li>
				<% else %>
					<li class="active"><a>Publication Info</a></li>
				<% end %>	

				<% unless current_page?(document_document_photos_path(@document)) %>
					<li><%= link_to("Item Images", document_document_photos_path(@document)) %></li>
				<% else %>
					<li class="active"><a>Item Images</a></li>
				<% end %>	

				<% unless current_page?(document_people_path(@document)) %>
					<li><%= link_to("People & Events", document_people_path(@document)) %></li>
				<% else %>
					<li class="active"><a>People & Events</a></li>
				<% end %>	

				<% unless current_page?(document_locations_path(@document)) %>
					<li><%= link_to("Locations", document_locations_path(@document)) %></li>
				<% else %>
					<li class="active"><a>Locations</a></li>
				<% end %>	

			<% else %>
				<li class="active"><a href="#">Item Details</a></li>
				<!--
				<li><a href="#">Publication Info</a></li>
				<li><a href="#">Item Images</a></li>
				<li><a href="#">Locations</a></li>
				<li><a href="#">People & Events</a></li>
				-->
			<%end%>
		</ul>

	</div>
</div>

app/views/documents/_warmemorial_form.html.erb
<div class="row-fluid">
	<%= render :partial => "warmemorial_menu"%>
</div>

<%= form_for @document, :html=>{ :multipart => true}  do |f| %>
	<div class="row-fluid form-horizontal">
			<%= render :partial => "shared/validationerror" ,:locals=>{:obj=>@document}%>
			<%= render :partial => 'warmemorial_item_details', :locals => {:f => f}  %>
	</div>		
	<br />

	<div class="row-fluid">
		<div class="span9"><h5 class="pull-right text-info">When you have finished adding information about your item, click the button on the right to continue</h5></div>
		<div class="span1"><i class="icon-hand-right" style="margin-top:10px;"></i></div> 
		<div class="span2">	  <%= f.submit "Next >" ,:class=>"btn" %></div>
	</div>

<% end %>

app/views/documents/_warmemorial_menu.html.erb
<div class="navbar">
	<div class="navbar-inner">

		<ul class="nav nav-bar">
			<% unless @document.new_record? %>
				<li><%= link_to_unless_current("View Item", document_path(@document))  %></li>
				<% unless current_page?(edit_document_path(@document)) %>
					<li><%= link_to_unless_current("Item Details", edit_document_path(@document)) %></li>
				<% else %>
					<li class="active"><a>Item Details</a></li>
				<% end %>	
			<% end %>

			<% unless @document.new_record? %>

				<% unless current_page?(document_document_photos_path(@document)) %>
					<li><%= link_to("Item Images", document_document_photos_path(@document)) %></li>
				<% else %>
					<li class="active"><a>Item Images</a></li>
				<% end %>	

				<% unless current_page?(document_people_path(@document)) %>
					<li><%= link_to("People & Events", document_people_path(@document)) %></li>
				<% else %>
					<li class="active"><a>People & Events</a></li>
				<% end %>	
			<% else %>
				<li class="active"><a href="#">Item Details</a></li>
			<%end%>
		</ul>

	</div>
</div>

app/views/documents/authorinfo.html.erb
<% @pagetitle = "Edit " + page_title %>
<% sub_title = "Publication Information" %>

<div class="well">
	<div class="row-fluid">
			<h4><%= @pagetitle %></h4>
			<h6><%= sub_title %></h6>
	</div>
</div>

<div class="row-fluid">
	<%= render :partial => "form_menu"%>
</div>

<legend>Publication Information</legend>

<div class="row-fluid form-horizontal">
	<%= form_for @document,:url=> :document_authorinfo, :html=>{:method=>:post, :multipart => true}  do |f| %>
		<%= render :partial => "shared/validationerror" ,:locals=>{:obj=>@document}%>
		<%= f.fields_for :document_attributes do |doc_attr| %>
				<%= render :partial => 'document_attribute_fields', :locals => {:f => doc_attr}  %>
		<% end %>

		<div class="row">
			<div class="span7"></div>
			<%= f.submit "Save",:class=>"span2 btn" %>
			<div class="span2 btn"><%= link_to_add_fields "Add More", f, :document_attributes %></div>

			<%#= link_to "Next", document_itemimages_path(@document),:class=>"span2 btn pull-right"%>
		</div>
	<% end %>
</div>	

app/views/documents/index.html.erb
<div class="alert alert-info">
  <div class="lead ">
    <div class="span7"><%= @pagetitle %></div>
    <div class="span5 pull-right"><%#= page_entries_info @documents %></div>
  </div>
</div>

<div class="search_results_container">
  <div class="row-fluid">
    <div class="pull-left">
	    <%= link_to "Back" ,root_path,:class=>"btn"%>
    </div>

		<div class="row-fluid" style="margin-bottom:10px;">
		  <div class="pull-right">
		    <%= banner_ad %>
		  </div>
		</div>

  	<%= render :partial=>"documents/document_filter"%>

<!-- Container -->
<div >
  <%= render :partial=>"documents/document_common_list"%>
  <%= will_paginate @documents ,:renderer => BootstrapLinkRenderer %>
</div>

app/views/documents/locations.html.erb
<% @pagetitle = "Edit " + page_title %>
<% sub_title = "Locations" %>

<div class="well">
	<div class="row-fluid">
			<h4><%= @pagetitle %></h4>
			<h6><%= sub_title %></h6>
	</div>
</div>

<div class="row-fluid">
	<%= render :partial => "form_menu"%>
</div>

<legend>Locations</legend>

<div class="row-fluid">
	<div class="accordion">





		<% @locations.each do |location| %>
			<% unless location.new_record? %>
				<h3><a href="#"><%= location.full_location %></a></h3>
				<div>
					<% @location = location %>
					<%= form_for(@location, :url=>document_location_path(@document,@location), :method=>:put) do |f| %>
						<%= render :partial => "locations/form", :locals=>{:f=>f} %>
						<%= f.submit "Save",:class=>"span2 btn" %>
					<%end%>
					<br />		
					<%= link_to image_tag("deleteicon.png"),document_location_path(location.document.id,location),:method => :delete, :confirm => "Are you sure to delete?"  %>
				</div>	
			<% end %>			
		<%end%>

	</div> <!-- End Accordion -->
	
	<br />
	<%= link_to "Next" ,document_itempeople_path(@document),:class=>"btn pull-right"%>

</div>

<hr />

app/views/documents/new.html.erb
<% @pagetitle = "Add New Item" %>

<div class="well">
  <div class="row-fluid">
      <h4><%= @pagetitle %></h4>
  </div>
</div>

<%= render :partial =>'form' %>

app/views/documents/publications.html.erb
<div class="alert alert-info">
	<div class="lead ">
		<div class="span7"><%= @pagetitle %></div>
		<div class="span5 pull-right"><%#= page_entries_info @documents %></div>
	</div>
</div>

<div class="search_results_container">
	<div class="row-fluid">
		<div class="span2 pull-left"><%= link_to "Home" ,root_path,:class=>"btn"%></div>
		<div class="pull-right"><%= render :partial=>"documents/publications_date_filter"%></div>
		<!-- Container -->
	</div>	

	<% unless @documents.count == 0 %>
		<div class="well well-small" style="margin: 2px 0;">
			<div class="row-fluid">
				<div class="span1"></div>
				<div class="span2"><strong>Date</strong></div>
				<div class="span3"><strong>Title</strong></div>
				<div class="span2"><strong>Publisher</strong></div>
				<div class="span1"><strong>Pages</strong></div>
				<div class="span2"><strong>Size</strong></div>
				<div class="span1"><strong>Status</strong></div>
			</div>
		</div>
	<%end%>

		<% @documents.each do |document| %>
			<% unless document.is_deleted || document.is_hidden? %>
				<div class="well well-small" style="margin: 2px 0;">
					<div class="row-fluid">
						<div class="span1">
							<%= link_to image_tag(document.default_image.photo.url(:small)), document_path(document),:class=>"thumbnail" unless document.default_image.nil? %>
						</div>
						<div class="span2"><small><%= link_to document.publication_date(@date_format), document_path(document) rescue "no date" %></small></div>
						<div class="span3">
							<% if document.title.blank? %>
								<%= link_to document.name, document_path(document) %>
							<% else %>  
								<%= link_to document.title, document_path(document) %>
							<% end %>
						</div>
						<div class="span2"><%= document.publisher.short_details %></div>
						<div class="span1"><%= document.pages %></div>
						<div class="span2"><%= document.dimensions %></div>
						<div class="span1"><%= link_to document.document_status, document_path(document) %></div>
					</div>
				</div>
			<%end%> 
		<% end %>
		<%= will_paginate @documents ,:renderer => BootstrapLinkRenderer %>

		<div class="well" style="margin-bottom:10px; margin-top:20px; text-align:center;">
			<%if @documents.count==0%><h3 class="text-error">Sorry, no <%=@publication_type.pluralize %> matching that date were found</h3><%end%>
			<h4>Search our Partners for Historic Newspapers</h4>
			<br />
			<script language="javascript" type="text/javascript">
				var myTarget='http://track.webgains.com/click.html?wglinkid=243675&wgcampaignid=122233&js=0';
				var uri = 'http://track.webgains.com/link.html?wglinkid=243675&wgcampaignid=122233';
				document.write('<a href="'+myTarget+'" target="_blank" onMouseOver="window.status=\'http://www.historic-newspapers.co.uk\';return true;" onMouseOut="window.status=\'\'"><img src="'+uri+'" width="728" height="90" border="0" alt="Historic Newspapers - Original Newspaper Gifts"/></a>');
			</script>
		</div>

	</div>
</div>	

app/views/documents/show.html.erb
<%= render @document %>

<hr />
<div class="rowfluid">
	<div class="well">
  		<center><%= banner_ad %></center>
	</div>
</div>


app/views/documents/warmemorial_new.html.erb
<% @pagetitle = "Add New War Memorial" %>
<% type = 'warmemorial' %>

<div class="well">
  <div class="row-fluid">
      <h4><%= @pagetitle %></h4>
  </div>
</div>

<%= render :partial =>'warmemorial_form' %>